# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# SIMP 6.4      5.5      2.4    TBD
# PE 2018.1     5.5      2.4    2020-11 (LTS)
# PE 2019.2     6.17     2.5    2019-08 (STS)
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ==============================================================================

name: CI

# Controls when the action will run.
on:
  push: {}
  pull_request: {}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  validate:
    name: "Validation"
    runs-on: ubuntu-latest
    env:
      PUPPET_VERSION: "~> 6"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:           
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1  # ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}        
      - uses: actions/cache@v2
        with:
          path: .vendor
          key: ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-
      - name: "Bundle dependencies for Puppet ${{matrix.puppet.puppet_version}}"
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: "Validation"
        run: | 
          echo bundle exec rake syntax
          echo bundle exec rake lint
          echo bundle exec rake metadata_lint

    
  test:  # <-- can be anything
    name: "Spec/Unit Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: "SIMP 6.4/PE 2018.1"
            puppet_version: "~> 5.5.21"
            ruby_version: "2.4"
          - label: "PE 2019.2"
            puppet_version: "~> 6.17.0"
            ruby_version: "2.5"    
    env:
      PUPPET_VERSION: "${{matrix.puppet.puppet_version}}"    

    steps:
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
      - uses: actions/cache@v2
        with:
          path: .vendor
          key: ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-
      - name: "Bundle dependencies for Puppet ${{matrix.puppet.puppet_version}}"
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: "Run Spec/Unit tests for ${{matrix.puppet.label}}"
        run: "echo Hello, world!  ${{matrix.puppet.label}}"

  # TODO: only run when org member initiates action?      
  acceptance:  # <-- can be anything
    name: "Acceptance tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet:
          - label: "SIMP 6.4/PE 2018.1"
            puppet_version: "~> 5.5.21"
            ruby_version: "2.4"
          - label: "PE 2019.2"
            puppet_version: "~> 6.17.0"
            ruby_version: "2.5"    
    env:
      PUPPET_VERSION: "${{matrix.puppet.puppet_version}}"    

    steps:
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
      - uses: actions/cache@v2
        with:
          path: .vendor
          key: ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby${{matrix.puppet.ruby_version}}-
      - name: "Bundle dependencies for Puppet ${{matrix.puppet.puppet_version}}"
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: "Run Acceptance tests for ${{matrix.puppet.label}}"
        run: "echo Hello, world!  ${{matrix.puppet.label}}"
        run: | 
          echo bundle exec rake syntax
          echo bundle exec rake lint
          echo bundle exec rake metadata_lint
